### ISSUE TITLE
Error in running

### ISSUE THREAD

**Issue by yanmyokyaw** [mehranabi/beego-jwt-mysql#1]
# github.com/gbrlsnchs/jwt
..\github.com\gbrlsnchs\jwt\rsa.go:55:12: pub.Size undefined (type *rsa.PublicKey has no field or method Size)

All packages are get but it show this error.

When getting >go get github.com/gbrlsnchs/jwt
this error shown 
# github.com/gbrlsnchs/jwt
go\src\github.com\gbrlsnchs\jwt\rsa.go:55:12: pub.Size undefined (type *rsa.PublicKey has no field or method Size)

**Comment by mehranabi** [comment]
Hi, format your message to show codes properly, and also provide more context so I can help u then...

**Comment by yanmyokyaw** [comment]
When I command go get, it show this error...
![err](https://user-images.githubusercontent.com/22882603/53286412-717db380-379c-11e9-8d4b-2e63b87bbfb8.PNG)

**Comment by mehranabi** [comment]
Hey, reference to https://github.com/gbrlsnchs/jwt/issues/22#issuecomment-466646334 (from main repo) 
You need to update your Go installation...
Try `go version` and if it's under 1.11, then install new version of Go...

Also use `go get -u ... ` (use **u** flag) to install new packages or update old ones...
